### ISSUE TITLE
Allow injecting secrets into user-created pods

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/bundle-kubeflow#208]
Feature request to allow automatic sidecar integration for the jupyterhub notebook pods for example. 
Example:
A data scientists that has access to a notebook need to download data from an external storage solution. This solution has a special authentication mechanism like Kerberos that manage access to data. A sidecar container to the notebook pod can be a good solution to do automatic Kerberos authentication and provide the user with a token that allows him to download his data. 

This is a simple use case but it can be expanded to multiple other use cases.
We can use Istio to provide this mechanism or any other automatic sidecar integration mechanism.

**Comment by knkski** [comment]
I believe PodDefaults will meet this use case. As a concrete example, you would create a PodDefault that looks something like this:

```yaml
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-my-secret
spec:
 selector:
  matchLabels:
    addmysecret: "true"
 desc: "add my secret"
 env:
 - name: MY_SECRET
   value: /secret/my/secret.json
 volumeMounts:
 - name: my-secret-volume
   mountPath: /secret/my/
 volumes:
 - name: my-secret-volume
   secret:
    secretName: my-secret-name
```

Then, Jupyter will let you specify that a notebook server should be created with that PodDefault. When the notebook server is created by Kubernetes, the admission webhook controller (#207) will intercept it and add in the environment variable and volume defined in the PodDefault (`MY_SECRET` and `/secret/my` in the example above). To update the secret, you can just update the `secret/my-secret-name` Resource, and Kubernetes will automatically update the mounted volume with the new value.
